//user
export const CHANGE_REGISTRATION_STAGE = 'CHANGE_REGISTRATION_STAGE'
export const GET_PHONE_CODE_ERROR = 'GET_PHONE_CODE_ERROR'
export const SUBMIT_PHONE_CODE_ERROR = 'SUBMIT_PHONE_CODE_ERROR'
export const GET_EMAIL_CODE_ERROR = 'GET_EMAIL_CODE_ERROR'
export const SUBMIT_EMAIL_CODE_ERROR = 'SUBMIT_EMAIL_CODE_ERROR'
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const AUTH_USER = 'AUTH_USER'

//quiz
export const GET_POSITION = 'GET_POSITION'
export const GET_QUESTION = 'GET_QUESTION'
export const TOGGLE_QUESTION_MODAL = 'TOGGLE_QUESTION_MODAL'
export const CHANGE_TOTAL_SPENT_TIME = 'CHANGE_TOTAL_SPENT_TIME'
export const TOGGLE_LEADERBOARD_MODAL = 'TOGGLE_LEADERBOARD_MODAL'
export const GET_LEADERBOARD = 'GET_LEADERBOARD'
