//user
export const CHANGE_REGISTRATION_STAGE = 'CHANGE_REGISTRATION_STAGE'
export const GET_PHONE_CODE_ERROR = 'GET_PHONE_CODE_ERROR'
export const SUBMIT_PHONE_CODE_ERROR = 'SUBMIT_PHONE_CODE_ERROR'
export const GET_EMAIL_CODE_ERROR = 'GET_EMAIL_CODE_ERROR'
export const SUBMIT_EMAIL_CODE_ERROR = 'SUBMIT_EMAIL_CODE_ERROR'
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const AUTH_USER = 'AUTH_USER'

//quiz
